repos:
  - repo: local
    hooks:
      - id: basedpyright
        name: basedpyright
        entry: uv run basedpyright .
        language: system
        types: [python]
        pass_filenames: false
